import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useRef, useState } from "react";
import { motion } from "motion/react";
import {
  Sparkles, ShieldCheck, ShieldAlert, ListChecks, MessageCircleQuestion, Loader2, Phone,
  Upload, FileText, ImageIcon, X, Quote, Scale, MessageCircle,
} from "lucide-react";
import { SiteNav } from "@/components/site-nav";
import { SiteFooter } from "@/components/site-footer";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { useI18n } from "@/lib/i18n";
import { explainCoverage, type PolicyExplanation } from "@/lib/policy-explainer.functions";

export const WHATSAPP_URL = `https://wa.me/254719401804?text=${encodeURIComponent(
  "Hello Limiel Insurance, I have a question about my insurance cover. Please assist me.",
)}`;

export const Route = createFileRoute("/explain")({
  component: ExplainPage,
  head: () => ({
    meta: [
      { title: "Explain My Cover | Limiel Insurance Limited" },
      {
        name: "description",
        content:
          "Ask a coverage question, paste your policy wording or upload a PDF or photo of your policy and get a plain-language explanation.",
      },
      { property: "og:title", content: "Explain My Cover | Limiel Insurance Limited" },
      {
        property: "og:description",
        content: "Plain-language answers on cover, exclusions and next steps — with Limiel advisors on hand to confirm the details.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
});

const MAX_BYTES = 8 * 1024 * 1024;
const ACCEPT = ["application/pdf", "image/png", "image/jpeg", "image/webp", "image/gif"];

const copy = {
  en: {
    kicker: "Cover explainer",
    title: "Understand your cover in plain language",
    intro:
      "Ask a question, paste wording from your policy, or upload your policy document (PDF or photo). You'll get a clear summary with the exact wording that supports it.",
    questionLabel: "Your coverage question",
    questionPlaceholder: "e.g. Does my comprehensive motor cover pay for a cracked windscreen?",
    policyLabel: "Paste policy text (optional)",
    policyPlaceholder: "Paste the relevant section of your policy schedule or wording here…",
    uploadLabel: "Upload policy documents (optional)",
    uploadHint: "PDF, JPG, PNG or WebP · up to 3 files · 8 MB each",
    uploadBtn: "Choose files",
    tooBig: "is larger than 8 MB.",
    badType: "is not a PDF or image.",
    tooMany: "You can upload up to 3 files.",
    submit: "Explain my cover",
    working: "Reading your cover…",
    summary: "In short",
    highlights: "Relevant policy wording",
    covered: "Likely covered",
    exclusions: "Commonly excluded or limited",
    nextSteps: "Your next steps",
    questions: "Questions to ask your insurer",
    advisor: "Talk to a Limiel agent",
    whatsapp: "Ask on WhatsApp",
    reset: "Start over",
    empty: "Add a question, paste policy text or upload a document to begin.",
    disclaimerTitle: "Information only — not legal advice",
    disclaimer:
      "These explanations are generated by AI for general information. They are not legal, financial or claims advice, and they do not change your policy. Your insurer's policy document and terms always apply — confirm important details with a Limiel agent.",
  },
  sw: {
    kicker: "Mfafanuzi wa bima",
    title: "Elewa bima yako kwa lugha rahisi",
    intro:
      "Uliza swali, nakili maandishi ya bima yako, au pakia hati ya bima (PDF au picha). Utapata muhtasari pamoja na maneno halisi yanayouunga mkono.",
    questionLabel: "Swali lako kuhusu bima",
    questionPlaceholder: "mf. Bima yangu kamili ya gari inalipa kioo cha mbele kilichovunjika?",
    policyLabel: "Nakili maandishi ya bima (si lazima)",
    policyPlaceholder: "Nakili sehemu muhimu ya hati yako ya bima hapa…",
    uploadLabel: "Pakia hati za bima (si lazima)",
    uploadHint: "PDF, JPG, PNG au WebP · hadi faili 3 · MB 8 kila moja",
    uploadBtn: "Chagua faili",
    tooBig: "ni kubwa kuliko MB 8.",
    badType: "si PDF wala picha.",
    tooMany: "Unaweza kupakia hadi faili 3.",
    submit: "Fafanua bima yangu",
    working: "Tunapitia bima yako…",
    summary: "Kwa kifupi",
    highlights: "Maneno muhimu ya bima",
    covered: "Kinachoweza kulipwa",
    exclusions: "Kinachoachwa au kikomo",
    nextSteps: "Hatua zako zinazofuata",
    questions: "Maswali ya kumuuliza mtoa bima",
    advisor: "Zungumza na wakala wa Limiel",
    whatsapp: "Uliza kwa WhatsApp",
    reset: "Anza upya",
    empty: "Ongeza swali, nakili maandishi au pakia hati kuanza.",
    disclaimerTitle: "Kwa taarifa tu — si ushauri wa kisheria",
    disclaimer:
      "Maelezo haya yametolewa na AI kwa taarifa za jumla. Si ushauri wa kisheria, kifedha au wa madai, na hayabadilishi bima yako. Hati na masharti ya mtoa bima ndiyo yanayotumika — thibitisha maelezo muhimu na wakala wa Limiel.",
  },
} as const;

type UploadFile = { name: string; mime: string; base64: string; size: number };

function readAsBase64(file: File) {
  return new Promise<string>((resolve, reject) => {
    const r = new FileReader();
    r.onload = () => resolve(String(r.result).split(",")[1] ?? "");
    r.onerror = () => reject(r.error);
    r.readAsDataURL(file);
  });
}

function ExplainPage() {
  const { lang } = useI18n();
  const c = copy[lang] ?? copy.en;
  const run = useServerFn(explainCoverage);
  const fileRef = useRef<HTMLInputElement>(null);

  const [question, setQuestion] = useState("");
  const [policyText, setPolicyText] = useState("");
  const [files, setFiles] = useState<UploadFile[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<PolicyExplanation | null>(null);

  const onPick = async (list: FileList | null) => {
    if (!list) return;
    setError(null);
    const next = [...files];
    for (const f of Array.from(list)) {
      if (next.length >= 3) { setError(c.tooMany); break; }
      if (!ACCEPT.includes(f.type)) { setError(`${f.name} ${c.badType}`); continue; }
      if (f.size > MAX_BYTES) { setError(`${f.name} ${c.tooBig}`); continue; }
      if (f.size === 0) continue;
      next.push({ name: f.name, mime: f.type, size: f.size, base64: await readAsBase64(f) });
    }
    setFiles(next);
    if (fileRef.current) fileRef.current.value = "";
  };

  const onSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!question.trim() && !policyText.trim() && files.length === 0) {
      setError(c.empty);
      return;
    }
    setLoading(true);
    setError(null);
    setResult(null);
    try {
      const data = await run({
        data: {
          question, policyText, lang,
          files: files.map((f) => ({ name: f.name, mime: f.mime as "application/pdf", base64: f.base64 })),
        },
      });
      setResult(data);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  const sections: { key: "covered" | "exclusions" | "nextSteps" | "questionsForInsurer"; title: string; icon: React.ReactNode }[] = [
    { key: "covered", title: c.covered, icon: <ShieldCheck className="h-4 w-4 text-primary" /> },
    { key: "exclusions", title: c.exclusions, icon: <ShieldAlert className="h-4 w-4 text-secondary" /> },
    { key: "nextSteps", title: c.nextSteps, icon: <ListChecks className="h-4 w-4 text-primary" /> },
    { key: "questionsForInsurer", title: c.questions, icon: <MessageCircleQuestion className="h-4 w-4 text-secondary" /> },
  ];

  const Disclaimer = (
    <div className="flex gap-3 rounded-xl border border-accent/40 bg-accent/10 p-4 text-sm">
      <Scale className="mt-0.5 h-5 w-5 shrink-0 text-accent-foreground" />
      <div>
        <p className="font-semibold">{c.disclaimerTitle}</p>
        <p className="mt-1 text-muted-foreground">{c.disclaimer}</p>
      </div>
    </div>
  );

  const Ctas = (
    <div className="flex flex-wrap gap-3">
      <Button asChild className="gradient-hero-bg text-primary-foreground">
        <Link to="/contact"><Phone className="mr-2 h-4 w-4" /> {c.advisor}</Link>
      </Button>
      <Button asChild variant="outline">
        <a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">
          <MessageCircle className="mr-2 h-4 w-4" /> {c.whatsapp}
        </a>
      </Button>
      <Button asChild variant="ghost">
        <a href="tel:+254719401804">+254 713 268 806</a>
      </Button>
    </div>
  );

  return (
    <div className="min-h-screen">
      <SiteNav />
      <section className="mx-auto max-w-5xl px-4 py-16 sm:px-6 sm:py-20">
        <p className="inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-primary">
          <Sparkles className="h-4 w-4" /> {c.kicker}
        </p>
        <h1 className="mt-2 font-display text-3xl font-bold sm:text-5xl">{c.title}</h1>
        <p className="mt-4 max-w-2xl text-base text-muted-foreground sm:text-lg">{c.intro}</p>

        <div className="mt-6">{Disclaimer}</div>

        <form onSubmit={onSubmit} className="mt-8 grid gap-5">
          <div className="grid gap-2">
            <Label htmlFor="question">{c.questionLabel}</Label>
            <Textarea id="question" rows={3} value={question} onChange={(e) => setQuestion(e.target.value)} placeholder={c.questionPlaceholder} maxLength={4000} />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="policy">{c.policyLabel}</Label>
            <Textarea id="policy" rows={6} value={policyText} onChange={(e) => setPolicyText(e.target.value)} placeholder={c.policyPlaceholder} maxLength={20000} />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="docs">{c.uploadLabel}</Label>
            <div
              className="rounded-xl border-2 border-dashed p-5 text-center transition hover:border-primary"
              onDragOver={(e) => e.preventDefault()}
              onDrop={(e) => { e.preventDefault(); void onPick(e.dataTransfer.files); }}
            >
              <Upload className="mx-auto h-6 w-6 text-muted-foreground" />
              <p className="mt-2 text-xs text-muted-foreground">{c.uploadHint}</p>
              <Button type="button" variant="outline" size="sm" className="mt-3" onClick={() => fileRef.current?.click()}>
                {c.uploadBtn}
              </Button>
              <input id="docs" ref={fileRef} type="file" multiple accept={ACCEPT.join(",")} className="hidden" onChange={(e) => void onPick(e.target.files)} />
            </div>
            {files.length > 0 && (
              <ul className="grid gap-2">
                {files.map((f, i) => (
                  <li key={f.name + i} className="flex items-center justify-between rounded-lg border bg-card px-3 py-2 text-sm">
                    <span className="flex min-w-0 items-center gap-2">
                      {f.mime === "application/pdf" ? <FileText className="h-4 w-4 shrink-0 text-primary" /> : <ImageIcon className="h-4 w-4 shrink-0 text-primary" />}
                      <span className="truncate">{f.name}</span>
                      <span className="shrink-0 text-xs text-muted-foreground">{(f.size / 1024 / 1024).toFixed(1)} MB</span>
                    </span>
                    <button type="button" aria-label={`Remove ${f.name}`} onClick={() => setFiles(files.filter((_, j) => j !== i))}>
                      <X className="h-4 w-4 text-muted-foreground" />
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </div>
          <div className="flex flex-wrap items-center gap-3">
            <Button type="submit" disabled={loading} className="gradient-hero-bg text-primary-foreground shadow-soft">
              {loading ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> {c.working}</> : <><Sparkles className="mr-2 h-4 w-4" /> {c.submit}</>}
            </Button>
            <Button asChild type="button" variant="outline">
              <a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer"><MessageCircle className="mr-2 h-4 w-4" /> {c.whatsapp}</a>
            </Button>
            {(result || error) && !loading && (
              <Button type="button" variant="ghost" onClick={() => { setResult(null); setError(null); setQuestion(""); setPolicyText(""); setFiles([]); }}>
                {c.reset}
              </Button>
            )}
          </div>
        </form>

        {error && <p className="mt-6 rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{error}</p>}

        {result && (
          <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mt-10 grid gap-5">
            <Card className="shadow-soft">
              <CardHeader className="pb-2"><CardTitle className="text-base">{c.summary}</CardTitle></CardHeader>
              <CardContent className="text-sm leading-relaxed text-muted-foreground">{result.summary}</CardContent>
            </Card>

            {result.highlights.length > 0 && (
              <Card className="shadow-soft">
                <CardHeader className="pb-2">
                  <CardTitle className="flex items-center gap-2 text-base"><Quote className="h-4 w-4 text-primary" /> {c.highlights}</CardTitle>
                </CardHeader>
                <CardContent className="grid gap-3">
                  {result.highlights.map((h, i) => (
                    <div key={i} className="rounded-lg border-l-4 border-accent bg-muted/40 p-3">
                      <p className="text-sm"><mark className="rounded bg-accent/30 px-1 text-foreground">“{h.quote}”</mark></p>
                      <p className="mt-2 text-sm text-muted-foreground">{h.meaning}</p>
                      <p className="mt-1 text-xs text-muted-foreground/80">— {h.source}</p>
                    </div>
                  ))}
                </CardContent>
              </Card>
            )}

            <div className="grid gap-5 md:grid-cols-2">
              {sections.map((s) => {
                const items = result[s.key] ?? [];
                if (items.length === 0) return null;
                return (
                  <Card key={s.key} className="shadow-soft">
                    <CardHeader className="pb-2"><CardTitle className="flex items-center gap-2 text-base">{s.icon} {s.title}</CardTitle></CardHeader>
                    <CardContent>
                      <ul className="space-y-2 text-sm text-muted-foreground">
                        {items.map((item, i) => (
                          <li key={i} className="flex gap-2"><span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-secondary" /><span>{item}</span></li>
                        ))}
                      </ul>
                    </CardContent>
                  </Card>
                );
              })}
            </div>

            {result.confidenceNote && (
              <p className="rounded-xl border bg-muted/50 p-4 text-xs leading-relaxed text-muted-foreground">{result.confidenceNote}</p>
            )}
            {Disclaimer}
            {Ctas}
          </motion.div>
        )}
      </section>
      <SiteFooter />
    </div>
  );
}
